[versions]
kotlin = "1.9.10"
androidGradlePlugin = "8.2.0"
core-ktx = "1.12.0"
appcompat = "1.7.1"
material = "1.9.0"
play-services-location = "21.0.1"

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
